Rl xml at
crazymykl/ex-em-elm pull request #2
Opened 2017-01-20 20:10 UTC by mrlevitas

query XML tree via list of strings for tags
includes test

2017-01-23 15:54 UTC, crazymykl requested changes
Definitely want more tests, indicative of the proper usage patterns of these decoders. Looks like it's heading in a positive direction, though!

2017-01-23 15:54 UTC, crazymykl commented on src/ExEmElm/Types.elm
> +textOfNode : Node -> String
CDATA is also text, but with less need for escaping.

2017-01-23 15:54 UTC, crazymykl commented on src/ExEmElm/Traverse.elm
> +                    List.concatMap (\n -> at n xs) children
The lambda could be eta-reduced to `(flip at xs)`.

2017-01-23 15:54 UTC, crazymykl commented on tests/Tests.elm
> +    describe "It queries the xml tree"
We want way more test cases.

2017-01-23 15:54 UTC, crazymykl commented on src/ExEmElm/Types.elm
> +            ""
Not sure about the use of `""` as a sentinel. Have you considered using `Maybe String` as a return type?

2017-01-23 15:54 UTC, crazymykl commented on src/ExEmElm/Types.elm
> +            ""
Ibid.

2017-01-23 20:24 UTC, mrlevitas commented on tests/Tests.elm
> +    describe "It queries the xml tree"
added

2017-01-23 20:25 UTC, mrlevitas commented on src/ExEmElm/Traverse.elm
> +                    List.concatMap (\n -> at n xs) children
addressed

2017-01-23 20:25 UTC, mrlevitas commented on src/ExEmElm/Types.elm
> +            ""
yep

2017-01-23 20:25 UTC, mrlevitas commented on src/ExEmElm/Types.elm
> +textOfNode : Node -> String
added a separate function `cdataOfNode` in Types

2017-01-23 20:25 UTC, mrlevitas commented on src/ExEmElm/Types.elm
> +            ""
addressed

2017-01-23 20:27 UTC, mrlevitas commented on tests/Tests.elm
> +    """<id>100947</id><id>100946</id><id>90158</id><id>90157</id><id>90187</id><id>90159</id><id>87975</id>"""
@crazymykl Is this xml that is returned correct?

2017-01-23 20:27 UTC, mrlevitas commented on tests/Tests.elm
> +    """<name>5 Store Report</name><name>AAA New filter Montevideo</name><name>Current VMM Stores- HS</name><name>Current live stores</name><name>Launch stores</name><name>None</name><name>Washington
@crazymykl Is this xml that is returned correct?

2017-01-23 22:25 UTC, crazymykl commented on tests/Tests.elm
> +    """<name>5 Store Report</name><name>AAA New filter Montevideo</name><name>Current VMM Stores- HS</name><name>Current live stores</name><name>Launch stores</name><name>None</name><name>Washington
Looks it.

2017-01-24 14:52 UTC, crazymykl commented on src/ExEmElm/Types.elm
> +cdataOfNode : Node -> Maybe String
CDATA is just text, this belongs in `textOfNode`

2017-01-24 19:58 UTC, mrlevitas commented on src/ExEmElm/Types.elm
> +cdataOfNode : Node -> Maybe String
addressed

2017-01-24 21:16 UTC, crazymykl approved these changes

2017-01-24 21:43 UTC, merged